### PR TITLE
bridge_skeleton/

### PR DESCRIPTION
**Pull request by phygicartindia**

### CODE REVIEW

**Comment by hafzalabbas** [comment]
wt5wetw

**Comment by hafzalabbas** [comment]
opncart

**Comment by phygicartindia** [comment]
oob/__manifest__.py
oob/models/__init__.py
oob/models/attribute_sync.py
oob/models/connector_snippet.py
oob/models/ecomm_status_sync.py
oob/models/product.py
oob/models/product_sync.py
oob/models/stock_move.py
oob/static/description/icon-features.png
oob/static/description/icon-help.png
oob/static/description/icon-support.png
oob/static/description/icon.png
oob/static/description/index.html
oob/static/src/img/icon.png

**Comment by hafzalabbas** [comment]
y

**Comment by hafzalabbas** [comment]
#

**Comment by hafzalabbas** [comment]
y #1 #

**Pull request closed without merging**
